const DB='BlueWalletFoundationDB',STORE='documents';let db,docs=[],cat='passport',modal=false,pinBuffer='';const cats=['passport','cdc','coc','visa','certificate','medical','other'];
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:'id'});r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
function allDocs(){return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
function putDoc(d){return new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(d);r.onsuccess=res;r.onerror=()=>rej(r.error)})}
function delDoc(id){return new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).delete(id);r.onsuccess=res;r.onerror=()=>rej(r.error)})}
const days=d=>d?Math.ceil((new Date(d)-new Date(new Date().toDateString()))/86400000):null;function stat(d){if(!d.expiry)return'No expiry';const x=days(d.expiry);return x<0?'Expired':x<=90?`${x}d left`:'Valid'}
async function hashPin(pin){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode('bw-foundation:'+pin));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function verifyPin(pin){return await hashPin(pin)===localStorage.getItem('bwfPinHash')}
function locked(){return localStorage.getItem('bwfPinHash')&&sessionStorage.getItem('bwfUnlocked')!=='1'}
function render(){if(locked())return renderLock();const list=docs.filter(d=>d.type===cat);const exp=docs.filter(d=>days(d.expiry)>=0&&days(d.expiry)<=90).length, old=docs.filter(d=>days(d.expiry)<0).length;document.querySelector('#app').innerHTML=`<header class="top"><div class="brand">THE BLUE WALLET<div class="sub">SPRINT 0.2 FOUNDATION</div></div><button class="btn" id="backup">Backup</button><button class="btn" id="settings">⚙</button></header><main class="shell"><div class="banner">Status: <b class="${navigator.onLine?'online':'offline'}">${navigator.onLine?'Online · offline cache ready':'Offline mode'}</b></div><section class="card stats"><div class="stat"><b>${docs.length}</b><div>Total</div></div><div class="stat"><b>${exp}</b><div>Expiring</div></div><div class="stat"><b>${old}</b><div>Expired</div></div></section><div class="tabs">${cats.map(c=>`<button class="btn tab ${c===cat?'active':''}" data-cat="${c}">${c.toUpperCase()} ${docs.filter(d=>d.type===c).length}</button>`).join('')}</div><section class="docs">${list.length?list.map(d=>`<article class="card doc"><div><b>${esc(d.title)}</b><br><small>${esc(d.number||'')} · ${stat(d)}</small></div><button class="btn danger" data-del="${d.id}">Delete</button></article>`).join(''):`<div class="card empty">No ${cat} documents yet.</div>`}</section></main><button class="btn primary fab" id="add">+</button>${modal?formHtml():''}`;bind()}
function formHtml(){return `<div class="modal"><form class="sheet" id="form"><h2>Add document</h2><div class="field"><label>Type</label><select id="type">${cats.map(c=>`<option ${c===cat?'selected':''}>${c}</option>`).join('')}</select></div><div class="field"><label>Title</label><input id="title" required></div><div class="row"><div class="field"><label>Number</label><input id="number"></div><div class="field"><label>Expiry</label><input id="expiry" type="date"></div></div><div class="field"><label>Scan / PDF</label><input id="file" type="file" accept="image/*,application/pdf" capture="environment"></div><div class="actions"><button type="button" class="btn" id="cancel">Cancel</button><button class="btn primary">Save</button></div></form></div>`}
function bind(){document.querySelectorAll('[data-cat]').forEach(x=>x.onclick=()=>{cat=x.dataset.cat;render()});$('#add').onclick=()=>{modal=true;render()};$('#cancel')&&($('#cancel').onclick=()=>{modal=false;render()});$('#form')&&($('#form').onsubmit=saveForm);document.querySelectorAll('[data-del]').forEach(x=>x.onclick=async()=>{if(confirm('Delete document?')){await delDoc(x.dataset.del);docs=await allDocs();render()}});$('#backup').onclick=backup;$('#settings').onclick=settings}
async function saveForm(e){e.preventDefault();let attachment=null;const f=$('#file').files[0];if(f){if(f.size>25*1024*1024)return alert('Maximum file size is 25 MB');attachment={name:f.name,type:f.type,data:await fileData(f)}}await putDoc({id:crypto.randomUUID(),type:$('#type').value,title:$('#title').value.trim(),number:$('#number').value.trim(),expiry:$('#expiry').value||null,attachment,createdAt:new Date().toISOString()});docs=await allDocs();cat=$('#type').value;modal=false;render()}
function fileData(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(f)})}
function backup(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({version:'0.2-foundation',docs},null,2)],{type:'application/json'}));a.download='blue-wallet-foundation-backup.json';a.click()}
async function settings(){const p=prompt('Set/change PIN (4–6 digits). Leave blank to cancel.');if(p===null||p==='')return;if(!/^\d{4,6}$/.test(p))return alert('PIN must be 4–6 digits');localStorage.setItem('bwfPinHash',await hashPin(p));localStorage.setItem('bwfPinLength',String(p.length));sessionStorage.setItem('bwfUnlocked','1');alert('PIN saved')}
function renderLock(){const len=Number(localStorage.getItem('bwfPinLength')||6);document.querySelector('#app').innerHTML=`<div class="lock"><div><h1>⚓<br>THE BLUE WALLET</h1><p>Enter your ${len}-digit PIN</p><div class="dots">${'○'.repeat(pinBuffer.length)}${'·'.repeat(Math.max(0,len-pinBuffer.length))}</div><p id="err"></p><div class="pad">${[1,2,3,4,5,6,7,8,9,'⌫',0,'✓'].map(k=>`<button class="btn key" data-key="${k}">${k}</button>`).join('')}</div></div></div>`;document.querySelectorAll('[data-key]').forEach(b=>b.onclick=async()=>{const k=b.dataset.key;if(k==='⌫')pinBuffer=pinBuffer.slice(0,-1);else if(k==='✓'){if(pinBuffer.length!==len)return $('#err').textContent=`Enter all ${len} digits`;if(await verifyPin(pinBuffer)){sessionStorage.setItem('bwfUnlocked','1');pinBuffer='';render()}else{$('#err').textContent='Wrong PIN';pinBuffer=''}}else if(pinBuffer.length<len)pinBuffer+=k;renderLock()})}
window.addEventListener('online',render);window.addEventListener('offline',render);if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');openDB().then(async()=>{docs=await allDocs();render()}).catch(e=>{document.querySelector('#app').innerHTML='<div class="empty">Storage failed: '+esc(e.message)+'</div>'});
